### ISSUE TITLE
Cannot uploaded scanner results to hub.mixeway.io

### ISSUE THREAD

**Issue by woznik** [Mixeway/MixewayScanner#7]
Hello
I give a try to upload the scanner results to `https://hub.mixeway.io/` but sadly I got a reposnse: `500 Internal server error`

![image](https://user-images.githubusercontent.com/17202024/112527435-5595d300-8da3-11eb-8883-9ba087158709.png)

I followed the tutorial part 5 and integrated gitlab and mixeway.io to upload the results

Is the server running?

**Comment by siewer** [comment]
Is it possible that location under test is not git repository (does .git directory exist?) and have set remote url? I will issue patch for hub.mixeway.io, because http 500 shouldn't be thrown anyway

**Comment by siewer** [comment]
Should be fixed. New version of hub.mixeway.io is already available, please test and reopen issue if error is still there
